### ISSUE TITLE
Fluterus bad spawn location

### ISSUE THREAD

**Issue by Y0lk** [nospoone/holobunnies-issues#19]
Sometimes, Fluterus will spawn what seems to be one tile too high. The battle works and he runs from left to right, but floating above the ground

**Comment by nospoone** [comment]
Not able to reproduce... 

@Psyae: did this happen to you?

**Comment by Psyae** [comment]
I did have this happen to me once before but never tried to reproduce. I believe I have video of it so I can look back at it later tonight and see what might be causing it.

**Comment by nospoone** [comment]
If you have a chance to do so I'd be grateful :cake:

**Comment by Psyae** [comment]
Go into Fluterus room, do not engage boss, kill yourself on spikes or stand on boss. When you respawn he's one tile higher

**Comment by nospoone** [comment]
Good work! Not sure how I didn't think about this...

**Comment by nospoone** [comment]
This should be fixed in `0.0.3`. Please reopen if you encounter this again!
