### ISSUE TITLE
Black screen after killing Shepherd

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#20]
Holobunnies PC: after beating Shepherd the screen goes black and stays black. You can still control the character but cannot see anything. You can kill yourself to fix it, but then you're just stuck in the Shepherd room with no where to go.

**Comment by moshiz** [comment]
Please don't kill yourself over the game

**Comment by nospoone** [comment]
What version are you running on?

**Comment by Psyae** [comment]
This was from the previous build before the latest update. Looks good now
