### ISSUE TITLE
Fluterus still very much alive

### ISSUE THREAD

**Issue by Y0lk** [nospoone/holobunnies-issues#23]
When Fluterus dies, sometimes he will still be standing still, with his move animation. The thing he does where he stop moving and there's a guitar sound effet will still trigger every 5 sec or so

**Comment by nospoone** [comment]
Any way to reproduce or did it just happen randomly?

**Comment by Y0lk** [comment]
No way to reproduce so far =/

**Comment by Psyae** [comment]
It can be replicated if you kill Flutterus as he is coming up from when he stops to go on the ground

**Comment by nospoone** [comment]
This should be fixed in `0.0.3`. Please reopen if you encounter this again!
