### ISSUE TITLE
Hub Music Keeps Playing

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#25]
Hub music keeps playing in boss rush if you attempt to start the simulation and immediately try to backout of the computer 

Might not be worth looking into though because no one would probably do this aside from me. Was just trying to break things

**Comment by nospoone** [comment]
Good catch!

**Comment by nospoone** [comment]
I'm unable to reproduce this - you press Confirm and then Back immediately?

**Comment by Psyae** [comment]
I'm using the PS4 controller, but once I hit the button to confirm start of the boss rush, I keep mashing the square button as fast as possible so the computer closes out. Even after the computer closes out, the game stills loads into boss rush but the hub music plays.

**Comment by Psyae** [comment]
I can double check later tonight that I can replicate it some more, but I also def have video in case there are some other factors that trigger this

**Comment by Psyae** [comment]
I RECORD EVERYTHING JUST IN CASE THERE IS SOME TYPE OF GLITCH SO THAT I CAN ANALYZE AND REPLICATE. I GOT YOUR BACK, ROMEO.

**Comment by nospoone** [comment]
Alright, I've put in a check for the music. I wasn't able to reproduce, but that should (maybe) fix it! :+1:

**Comment by nospoone** [comment]
Feel free to reopen this, should you be able to do this in the next patch (0.0.3) :+1:
