### ISSUE TITLE
Animation Glitch on Slopes

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#28]
When idling on slopes it causes the character to behave oddly. Bunnies are standing in place with the animation constantly changing/shaking. I've attempted to capture this in OBS but the animations happen to quickly that it was unable to pick it up properly. Looking at the vid, it just shows the falling face of the bunny I'm playing as.

**Comment by nospoone** [comment]
Yes, I can confirm this is happening :+1:

**Comment by nospoone** [comment]
I implemented a fix that _might_ fix this. Let me know if you see this happening again.
