### ISSUE TITLE
Character Facing Opposite Direction of Movement

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#29]
Was trying to figure out how to make my keyboard work, but then gave up. When I came back to the controller that was Leenox (after he died a few times), I saw that I was facing the opposite direction I was moving. It seemed to correct itself when going the other way

Didn't really bother trying to reproduce this one, but I figure this video might help you understand some things: https://www.youtube.com/watch?v=LRSvdKI4NH4 (sorry for the long period of nothing happening in the beginning, but I figure it might be useful to you in some way)

**Comment by nospoone** [comment]
Ah, the good 'ol moonwalk mode.

**Comment by nospoone** [comment]
This should be fixed in `0.0.3`. Please reopen if you encounter this again!
