### ISSUE TITLE
Olduvis Red Health Bar Remains

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#31]
You can make the red of the health bar stay at the top of the screen if you kill yourself on the hazard that you're supposed to make him slam down on. 

Kill yourself on the hazard, you go through the death animation as he slams down, and then when you respawn the red of his health bar will remain but his name and the white of the bar are gone. Once he slams down after you respawn and the fight actually begins all is normal.

**Comment by Psyae** [comment]
I imagine this can be replicated on any boss battle if you kill yourself as their health bar is appearing.

**Comment by Psyae** [comment]
Just attempted with Shepherd and Fluterus. Causes a game crash if you shoot in their direction and go through death animation as the bullet reaches them.

**Comment by nospoone** [comment]
This is actually two bugs. Thanks!
