### ISSUE TITLE
Black Screen After Shepherd Kill

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#33]
Killed Shepherd of Fire, after Victory Achieved came on the screen and it went black, nothing else happened. Just black. Turns out I was still able to control Danielle. Walked into the lava, and as I respawned Shepherd was just in mid air flashing, can just walk through him. Looking at the video the only thing that I could tell that happened that could have possibly caused this was that he just spit out fire balls (or whatever they are) as he was dying. As his health bar and name disappeared, the fire balls disappeared too.

Note: I had something similar to this happen to me in the first version of the game but upon killing myself the game crashed.

**Comment by nospoone** [comment]
Good catch, this happens only when you _don't_ play Ranked.
