### ISSUE TITLE
Clipping through Leaves

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#34]
Noticed in the caves when there are leaves coming out of the ceiling, if you jetpack to touch the ceiling, you'll go straight through the leaves. (I hope that makes sense?)

**Comment by nospoone** [comment]
@moshiz 
We have to move the `Ground` layers to the foreground:
![image](https://cloud.githubusercontent.com/assets/708588/17645923/a88b0ab0-6181-11e6-93f3-3c6cdc0fb1a6.png)
