### ISSUE TITLE
(Audio) settings resetting when returning to "cafe"

### ISSUE THREAD

**Issue by khalednkidu** [nospoone/holobunnies-issues#44]
## General Info

Operating System  : Windows
Version #         : 10
Optional Info     : ehhh nothing
## Reproduction/Behavior

**Steps to reproduce:**
1.Change music volume silder all the way down to 0
2.Music is gone. Good.
3.Enter the game menu (use the pc)
4.Open something like scoreboard
5.Return to cafe

**Expected behavior:**
Sound to remain same

**What happened:**
Sound is loud again and settings are reset, but if you go to options the slider is still on 0.

**Comment by nospoone** [comment]
Just found out this also happens if you close the game and come back.
