### ISSUE TITLE
PC: PS4 Controller Not Recognized

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#56]
I'm using the newer version of the PS4 controller. It isn't being recognized by Pause Cafe. Other games it works fine.

**Comment by nospoone** [comment]
Damn. I use an old version of the DS4 myself for testing. Can you show me what your Game Controllers panel looks like?

![image](https://cloud.githubusercontent.com/assets/708588/23098161/b1d1be42-f615-11e6-8efa-68ce9bd65de1.png)

You can access this via the start menu by searching for _game_ - it should come up as "Set up USB game controllers".

**Comment by nospoone** [comment]
We discussed this via Hangouts - seems like the communication protocol between the New DS4 and the previous iteration is different and not supported by OpenFL/HF

Looking into it...

**Comment by nospoone** [comment]
Moving this into 2.0.0 as we are switching engines - this will most likely be fixed as a result of this.

**Comment by nospoone** [comment]
I can confirm this is fixed in the Windows build of the Unity version of the game.
