### ISSUE TITLE
PC: Computer Menu Glitch

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#60]
If you select a game mode then hit back then try to select something different, it behaves oddly.

Example: Hit space for Boss Rush. Hit enter to go back, hitting up on the arrow key once does nothing. Hit it a second time it goes up.

Hit space for Runner. Hit enter to go back, hitting up on arrow key goes down instead. Hit it a second time and it behaves normally again.

**Comment by Psyae** [comment]
Also, if you hit space for runner, go back, hit space again while still highlighted on runner, it'll take you to the brawl options

**Comment by nospoone** [comment]
The problem here is that the cursor resets it position to the top, but does not update the visuals. 👍
