### ISSUE TITLE
PC: Music Not Playing In Runner

### ISSUE THREAD

**Issue by Psyae** [nospoone/holobunnies-issues#62]
Load up runner. Pause and return to title screen. Go back into runner and music will no longer play.

**Comment by Psyae** [comment]
Along with this, I think that pausing may prevent the track from looping once it's complete.

**Comment by Psyae** [comment]
Maybe not? I'm not too sure. I paused the game, the music didn't loop and it was silent for quite some time. I went to do some stuff with the game paused (I was taking screenshots of that hard level to try to figure out the route I need to take to actually complete it), and played the game for a bit, but at some point the level music started playing again.

**Comment by nospoone** [comment]
I was able to track down & fix the first issue - I'll look into looping

**Comment by Psyae** [comment]
May be caused by dying at the end of song? 

Tested on level where you're going up and up and up with spikes at the very beginning. Originally when testing my theory, it looped once (even though I think I died during transition). I don't know why I have this obsession with thinking that pausing the game changes things, but I decided to pause game, and as I died during end of a song, it did not loop.

**Comment by nospoone** [comment]
To clarify:

1. Wait until close to the end of the song
2. Die
3. Pause while dying

Makes the music stop. Correct?

**Comment by Psyae** [comment]
It wasn't pause while dying, it was just pause at any point in the level. 

1. Pause at any point in level
2. Die as music is ending
3. Music won't play

I don't fucking know about this anymore though. I'm unable to reproduce it now. I give up.

**Comment by nospoone** [comment]
I'll try that and see if I can make it happen. 

🤔

**Comment by Psyae** [comment]
Apparently I have video of one of the instances from last night:

https://www.youtube.com/watch?v=W4A72JAyhnI

Lemme know if you think you see what the issue might be, because I'm fucking stumped.

**Comment by nospoone** [comment]
Can't isolate a reason... I can hear that music doesn't even loop properly, though.

**Comment by Psyae** [comment]
It was sounding a bit off to me but I wasn't entirely sure (plus I think I took this video at like 1am so I was pretty out of it at that point.)

**Comment by nospoone** [comment]
Well, as it turns out, you found an engine bug. Looking into fixing it...

**Comment by nospoone** [comment]
The issue is two-fold: 

1. Losing focus and focusing back in will seemingly make the music start again from the point where it was when you unfocused, and won't make it loop again.
2. https://github.com/HaxeFlixel/flixel/issues/2040

I can "fix" the first problem by preventing the game from pausing when it loses focus. Would this be acceptable? (@Psyae @moshiz)

I will try to find the cause of the second problem as well.

**Comment by nospoone** [comment]
I also worked around the second problem by cutting the volume instead of actually pausing the sound. This will likely fix it.
