### ISSUE TITLE
When controller is plugged in, you cant access the computer.

### ISSUE THREAD

**Issue by eatyourmattress** [nospoone/holobunnies-issues#67]

**Comment by nospoone** [comment]
Thanks for the report. Does it open and close very quickly, or does it not open at all?

**Comment by eatyourmattress** [comment]
Yeah it opens and closes very quickly. I wasn't sure whether it was just me
or not so I posted just in case :)

**Comment by nospoone** [comment]
Yep, I was able to reproduce and fix. Thanks again! :+1:
